"""
Email utilities for CANSLIM Analyzer
Handles watchlist alerts and other email notifications
"""

import smtplib
import os
import logging
import requests
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

logger = logging.getLogger(__name__)

# Load .env file if it exists
def _load_env():
    """Load environment variables from .env file if it exists"""
    env_path = Path(__file__).parent.parent / '.env'
    if env_path.exists() and env_path.is_file():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

_load_env()

# Email configuration
GMAIL_ADDRESS = os.environ.get('CANSLIM_EMAIL', 'your-email@gmail.com')
GMAIL_APP_PASSWORD = os.environ.get('CANSLIM_APP_PASSWORD', 'your-app-password')
RECIPIENT_EMAIL = os.environ.get('CANSLIM_RECIPIENT', GMAIL_ADDRESS)


def send_email(subject: str, html_content: str, text_content: str) -> bool:
    """Send email via Gmail SMTP

    Args:
        subject: Email subject line
        html_content: HTML version of the email body
        text_content: Plain text version of the email body

    Returns:
        True if email sent successfully, False otherwise
    """
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = GMAIL_ADDRESS
    msg['To'] = RECIPIENT_EMAIL

    part1 = MIMEText(text_content, 'plain')
    part2 = MIMEText(html_content, 'html')
    msg.attach(part1)
    msg.attach(part2)

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, RECIPIENT_EMAIL, msg.as_string())
        logger.info(f"Email sent successfully to {RECIPIENT_EMAIL}")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


def send_watchlist_alert_email(item, stock, reasons: list) -> bool:
    """Send email when watchlist alert triggers

    Args:
        item: Watchlist model instance
        stock: Stock model instance
        reasons: List of reason strings

    Returns:
        True if email sent successfully, False otherwise
    """
    subject = f"CANSLIM Alert: {item.ticker}"

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }}
            .stock-info {{ background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 15px; }}
            .reason {{ background: #e7f5ff; padding: 10px; border-left: 4px solid #228be6; margin: 5px 0; }}
            .metric {{ display: inline-block; margin-right: 20px; }}
            .metric-value {{ font-size: 1.2em; font-weight: bold; }}
            .footer {{ color: #666; font-size: 0.9em; margin-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h2 style="margin: 0;">Watchlist Alert Triggered</h2>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">{item.ticker} has met your alert criteria</p>
        </div>

        <div class="stock-info">
            <h3 style="margin-top: 0;">{item.ticker} - {stock.name if stock.name else 'Unknown'}</h3>
            <div class="metric">
                <div style="color: #666;">Current Price</div>
                <div class="metric-value">${stock.current_price:.2f}</div>
            </div>
            <div class="metric">
                <div style="color: #666;">CANSLIM Score</div>
                <div class="metric-value">{stock.canslim_score:.0f}</div>
            </div>
        </div>

        <h3>Alert Reasons:</h3>
        {''.join(f'<div class="reason">{r}</div>' for r in reasons)}

        {f'<p><strong>Your Notes:</strong> {item.notes}</p>' if item.notes else ''}

        <div class="footer">
            <p>Generated by CANSLIM Analyzer</p>
        </div>
    </body>
    </html>
    """

    text_content = f"""Watchlist Alert: {item.ticker}

{item.ticker} - {stock.name if stock.name else 'Unknown'}

Reasons:
{chr(10).join(f'- {r}' for r in reasons)}

Current Price: ${stock.current_price:.2f}
CANSLIM Score: {stock.canslim_score:.0f}
{f'Your Notes: {item.notes}' if item.notes else ''}
"""

    return send_email(subject, html_content, text_content)


# Webhook configuration
WEBHOOK_URL = os.environ.get('CANSLIM_WEBHOOK_URL', '')


def send_webhook_notification(title: str, message: str, priority: str = "normal", data: dict = None) -> bool:
    """Send push notification via webhook (e.g., ntfy.sh, Pushover, or custom)

    The webhook receives a JSON payload with:
    - title: Notification title
    - message: Notification body
    - priority: "normal", "high", or "low"
    - data: Optional extra data dict

    Compatible with ntfy.sh, Pushover, Discord webhooks, and custom endpoints.

    Args:
        title: Notification title
        message: Notification body text
        priority: Priority level ("normal", "high", "low")
        data: Optional extra data to include in payload

    Returns:
        True if notification sent successfully, False otherwise
    """
    if not WEBHOOK_URL:
        logger.debug("Webhook URL not configured, skipping notification")
        return False

    payload = {
        "title": title,
        "message": message,
        "priority": priority,
    }
    if data:
        payload["data"] = data

    # Handle different webhook formats
    try:
        # Check for ntfy.sh style (topic-based URL)
        if "ntfy" in WEBHOOK_URL:
            # ntfy.sh uses a different format
            headers = {
                "Title": title,
                "Priority": "high" if priority == "high" else "default",
            }
            response = requests.post(WEBHOOK_URL, data=message.encode('utf-8'), headers=headers, timeout=10)
        else:
            # Standard JSON webhook (Pushover, Discord, custom)
            response = requests.post(WEBHOOK_URL, json=payload, timeout=10)

        if response.status_code in (200, 201, 204):
            logger.info(f"Webhook notification sent: {title}")
            return True
        else:
            logger.warning(f"Webhook returned status {response.status_code}: {response.text[:200]}")
            return False

    except requests.exceptions.Timeout:
        logger.error("Webhook request timed out")
        return False
    except requests.exceptions.RequestException as e:
        logger.error(f"Webhook request failed: {e}")
        return False


def send_coiled_spring_alert_webhook(stock, cs_result: dict) -> bool:
    """Send webhook notification for Coiled Spring alerts

    Args:
        stock: Stock model instance
        cs_result: Coiled Spring calculation result dict

    Returns:
        True if notification sent successfully, False otherwise
    """
    days_to_earnings = cs_result.get('days_to_earnings', 'N/A')
    base_type = cs_result.get('base_type', 'unknown')
    weeks = cs_result.get('weeks_in_base', 0)
    beat_streak = cs_result.get('beat_streak', 0)

    title = f"🌀 Coiled Spring: {stock.ticker}"
    message = (
        f"{stock.ticker} - {getattr(stock, 'name', 'Unknown')}\n"
        f"Price: ${stock.current_price:.2f}\n"
        f"Score: {stock.canslim_score:.0f}\n"
        f"Earnings in {days_to_earnings} days\n"
        f"Base: {base_type} ({weeks}w), {beat_streak} beat streak"
    )

    data = {
        "ticker": stock.ticker,
        "price": stock.current_price,
        "score": stock.canslim_score,
        "days_to_earnings": days_to_earnings,
        "base_type": base_type,
        "weeks_in_base": weeks,
        "beat_streak": beat_streak,
    }

    return send_webhook_notification(title, message, priority="high", data=data)


def send_trade_webhook(ticker: str, action: str, shares: float, price: float,
                       reason: str, gain_pct: float = None) -> bool:
    """Send webhook notification when AI trader executes a trade.

    Args:
        ticker: Stock ticker
        action: BUY or SELL
        shares: Number of shares
        price: Execution price
        reason: Trade reason
        gain_pct: Realized gain % (for sells)

    Returns:
        True if sent successfully
    """
    title = f"{'BUY' if action == 'BUY' else 'SELL'}: {ticker}"
    message = f"{ticker}: {shares:.2f} shares @ ${price:.2f}\n{reason}"
    if gain_pct is not None:
        message = f"{ticker}: {shares:.2f} shares @ ${price:.2f} ({gain_pct:+.1f}%)\n{reason}"

    return send_webhook_notification(title, message, priority="high")


def send_stop_loss_webhook(ticker: str, shares: float, price: float,
                           stop_type: str, loss_pct: float) -> bool:
    """Send urgent webhook when stop loss triggers.

    Args:
        ticker: Stock ticker
        shares: Shares sold
        price: Sell price
        stop_type: STOP LOSS or TRAILING STOP
        loss_pct: Loss percentage

    Returns:
        True if sent successfully
    """
    title = f"{stop_type}: {ticker}"
    message = f"{ticker}: {shares:.2f} shares @ ${price:.2f} ({loss_pct:+.1f}%)\nAutomatic stop triggered"

    return send_webhook_notification(title, message, priority="high")


def send_risk_alert_webhook(alert_type: str, details: str) -> bool:
    """Send webhook alert for portfolio risk conditions.

    Args:
        alert_type: Type of risk (heat, sector_concentration, position_size)
        details: Description of the risk condition

    Returns:
        True if sent successfully
    """
    titles = {
        "heat": "Portfolio Heat Warning",
        "sector_concentration": "Sector Concentration Alert",
        "position_size": "Position Size Alert",
        "drawdown": "Drawdown Warning",
    }
    title = titles.get(alert_type, f"Risk Alert: {alert_type}")
    return send_webhook_notification(title, details, priority="high")


def send_morning_briefing_email(briefing_data: dict) -> bool:
    """Send morning briefing email with portfolio status, market regime, and top candidates.

    Args:
        briefing_data: Dict containing:
            - portfolio: Portfolio value summary
            - market_regime: Current market regime info
            - positions: List of current position summaries
            - top_candidates: Top buy candidates for today
            - market_timing: FTD/A-D day status
            - portfolio_heat: Current portfolio heat %

    Returns:
        True if email sent successfully, False otherwise
    """
    portfolio = briefing_data.get("portfolio", {})
    regime = briefing_data.get("market_regime", {})
    positions = briefing_data.get("positions", [])
    candidates = briefing_data.get("top_candidates", [])
    timing = briefing_data.get("market_timing", {})
    heat = briefing_data.get("portfolio_heat", 0)
    earnings_this_week = briefing_data.get("earnings_this_week", [])

    total_value = portfolio.get("total_value", 0)
    total_return_pct = portfolio.get("total_return_pct", 0)
    cash = portfolio.get("cash", 0)
    regime_name = regime.get("regime", "unknown").upper()

    subject = f"CANSLIM Morning Briefing - ${total_value:,.0f} ({total_return_pct:+.1f}%)"

    # Build positions table rows
    pos_rows = ""
    for p in positions[:10]:
        color = "#16a34a" if p.get("gain_pct", 0) >= 0 else "#dc2626"
        pos_rows += f"""
        <tr>
            <td style="padding:6px 10px;">{p.get('ticker','')}</td>
            <td style="padding:6px 10px;">${p.get('price',0):.2f}</td>
            <td style="padding:6px 10px;color:{color};">{p.get('gain_pct',0):+.1f}%</td>
            <td style="padding:6px 10px;">{p.get('score',0):.0f}</td>
        </tr>"""

    # Build candidates rows
    cand_rows = ""
    for c in candidates[:5]:
        cand_rows += f"""
        <tr>
            <td style="padding:6px 10px;">{c.get('ticker','')}</td>
            <td style="padding:6px 10px;">${c.get('price',0):.2f}</td>
            <td style="padding:6px 10px;">{c.get('score',0):.0f}</td>
            <td style="padding:6px 10px;">{c.get('reason','')[:60]}</td>
        </tr>"""

    # Build earnings this week section
    earnings_rows = ""
    for e in earnings_this_week[:5]:
        ecolor = "#16a34a" if e.get("gain_pct", 0) >= 0 else "#dc2626"
        earnings_rows += f"""
        <tr>
            <td style="padding:6px 10px;">{e.get('ticker','')}</td>
            <td style="padding:6px 10px;">{e.get('days_to_earnings',0)}d</td>
            <td style="padding:6px 10px;">{e.get('beat_streak',0)} beats</td>
            <td style="padding:6px 10px;color:{ecolor};">{e.get('gain_pct',0):+.1f}%</td>
        </tr>"""
    earnings_section_html = ""
    if earnings_this_week:
        earnings_section_html = f'<div class="card"><h3 style="margin-top:0;">Earnings This Week</h3><table><tr><th>Ticker</th><th>Days</th><th>Streak</th><th>Gain</th></tr>{earnings_rows}</table></div>'

    timing_state = timing.get("state", "N/A")
    timing_color = "#16a34a" if timing.get("can_buy", True) else "#dc2626"
    regime_color = {"BULLISH": "#16a34a", "BEARISH": "#dc2626"}.get(regime_name, "#ca8a04")

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #1e40af 0%, #7c3aed 100%); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }}
            .card {{ background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 15px; }}
            table {{ width: 100%; border-collapse: collapse; }}
            th {{ background: #e2e8f0; padding: 8px 10px; text-align: left; font-size: 0.9em; }}
            .badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 0.85em; font-weight: bold; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h2 style="margin:0;">Morning Briefing</h2>
            <p style="margin:5px 0 0;opacity:0.9;">Portfolio: ${total_value:,.2f} ({total_return_pct:+.1f}%) | Cash: ${cash:,.2f}</p>
        </div>

        <div class="card">
            <h3 style="margin-top:0;">Market Status</h3>
            <p>Regime: <span class="badge" style="background:{regime_color};color:white;">{regime_name}</span>
               &nbsp; Timing: <span class="badge" style="background:{timing_color};color:white;">{timing_state}</span>
               &nbsp; Heat: {heat:.1f}%</p>
        </div>

        {'<div class="card"><h3 style="margin-top:0;">Current Positions (' + str(len(positions)) + ')</h3><table><tr><th>Ticker</th><th>Price</th><th>Gain</th><th>Score</th></tr>' + pos_rows + '</table></div>' if positions else ''}

        {'<div class="card"><h3 style="margin-top:0;">Top Buy Candidates</h3><table><tr><th>Ticker</th><th>Price</th><th>Score</th><th>Reason</th></tr>' + cand_rows + '</table></div>' if candidates else '<div class="card"><p>No buy candidates today.</p></div>'}

        {earnings_section_html}

        <div style="color:#666;font-size:0.85em;margin-top:20px;">
            <p>Generated by CANSLIM Analyzer</p>
        </div>
    </body>
    </html>
    """

    text_content = f"""CANSLIM Morning Briefing
Portfolio: ${total_value:,.2f} ({total_return_pct:+.1f}%) | Cash: ${cash:,.2f}
Regime: {regime_name} | Timing: {timing_state} | Heat: {heat:.1f}%

Positions ({len(positions)}):
{chr(10).join(f"  {p.get('ticker','')} ${p.get('price',0):.2f} {p.get('gain_pct',0):+.1f}% Score:{p.get('score',0):.0f}" for p in positions[:10])}

Top Candidates:
{chr(10).join(f"  {c.get('ticker','')} ${c.get('price',0):.2f} Score:{c.get('score',0):.0f} - {c.get('reason','')[:60]}" for c in candidates[:5])}

{("Earnings This Week:" + chr(10) + chr(10).join(f"  {e.get('ticker','')} in {e.get('days_to_earnings',0)}d, {e.get('beat_streak',0)} beats, {e.get('gain_pct',0):+.1f}%" for e in earnings_this_week[:5])) if earnings_this_week else ""}
"""

    return send_email(subject, html_content, text_content)
